server:
  port: 80
  servlet:
    context-path: /  
    
spring:
  application:
    name: static-service
    
#测试配置
  datasource:
    url: jdbc:mysql://www.duchaoqing.cn:3306/duchaoqing_db?characterEncoding=utf-8
    username: duchaoqing_db
    password: duchaoqing_mysql_mima
  thymeleaf:
    suffix: .html

    

